### PR TITLE
Add Greasemonkey manifest

### PR DESCRIPTION
**Pull request by tbodt**
This allows installing uBO-Extra on browsers that aren't Chrome (I use it with Safari.)

Note that the `@version` field will need to be updated when a new version is released, in addition to the version in manifest.json.

### CODE REVIEW

**Comment by jspenguin2017** [comment]
You'll be losing race conditions if you change it into an Userscript.

**Comment by tbodt** [comment]
Userscripts can be run before the DOM is loaded in the same fashion as content scripts. I've updated the manifest to do this.

**Comment by jspenguin2017** [comment]
If the Userscript manager is written in WebExtension, then that's not possible. Even if you put `document-start`, you'll still lose race condition. Otherwise, uBO-Extra wouldn't exist.

**Comment by tbodt** [comment]
What's the difference between a content script running at document start and a userscript running at document start?

**Comment by gorhill** [comment]
If I accept this pull request (assuming it worked as intended), it implies that I will accept to widen its purpose and also maintain it as a user script, which is not something I want to do.

**Comment by jspenguin2017** [comment]
Userscript can't run on the true `document-start`.

**Comment by gorhill** [comment]
Declined.

**Pull request closed without merging**
